# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5JLd5YjkNA5J_-2LitAv-Tfw1doeHqN
"""

!pip install transformers accelerate gradio -q

from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer
import torch

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="auto")
streamer = TextStreamer(tokenizer)

def chat_with_tinyllama(message, history):
    chat_prompt = ""
    for user_msg, bot_msg in history:
        chat_prompt += f"<|user|>\n{user_msg}\n<|assistant|>\n{bot_msg}\n"
    chat_prompt += f"<|user|>\n{message}\n<|assistant|>\n"

    inputs = tokenizer(chat_prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        eos_token_id=tokenizer.eos_token_id,
    )
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded.split("<|assistant|>")[-1].strip()

import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("## 🤖 TinyLLaMA Chatbot")
    chatbot = gr.Chatbot()
    msg = gr.Textbox(placeholder="Type your message here...")
    clear = gr.Button("Clear Chat")
    history = gr.State([])

    def respond(message, history):
        answer = chat_with_tinyllama(message, history)
        history.append((message, answer))
        return history, history

    msg.submit(respond, [msg, history], [chatbot, history])
    clear.click(lambda: ([], []), None, [chatbot, history])

demo.launch()